name: drivix-app-dev

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: drivix-backend-dev
    command: npm run dev
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    networks:
      - drivix-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: drivix-frontend-dev
    ports:
      - "5174:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - drivix-network

networks:
  drivix-network:
    driver: bridge
